### ISSUE TITLE
Double-check nginx' gzip_types

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-cm#71]
We currently have:
```
gzip_types application/x-javascript text/css text/plain application/xml image/svg+xml;
```
in `vhost.pp`.

I just noticed that the landing page mp4-video on paypal.com is around 50% smaller thanks to gzipped transfer.
@kris-lab @ppp0 let's double check which file types should be zipped.

cc @nicolasschmutz

**Comment by tomaszdurka** [comment]
This is pretty old issue, should we move it to puppet-packages or close? @njam you probably know the best.

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/puppet-packages/issues/824
